// Code generated by counterfeiter. DO NOT EDIT.
package httpfakes

import (
	httpnet "net/http"
	"sync"

	"github.com/Peripli/service-manager/pkg/security/http"
	"github.com/Peripli/service-manager/pkg/web"
)

type FakeAuthenticator struct {
	AuthenticateStub        func(req *httpnet.Request) (*web.UserContext, http.Decision, error)
	authenticateMutex       sync.RWMutex
	authenticateArgsForCall []struct {
		req *httpnet.Request
	}
	authenticateReturns struct {
		result1 *web.UserContext
		result2 http.Decision
		result3 error
	}
	authenticateReturnsOnCall map[int]struct {
		result1 *web.UserContext
		result2 http.Decision
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthenticator) Authenticate(req *httpnet.Request) (*web.UserContext, http.Decision, error) {
	fake.authenticateMutex.Lock()
	ret, specificReturn := fake.authenticateReturnsOnCall[len(fake.authenticateArgsForCall)]
	fake.authenticateArgsForCall = append(fake.authenticateArgsForCall, struct {
		req *httpnet.Request
	}{req})
	fake.recordInvocation("Authenticate", []interface{}{req})
	fake.authenticateMutex.Unlock()
	if fake.AuthenticateStub != nil {
		return fake.AuthenticateStub(req)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.authenticateReturns.result1, fake.authenticateReturns.result2, fake.authenticateReturns.result3
}

func (fake *FakeAuthenticator) AuthenticateCallCount() int {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	return len(fake.authenticateArgsForCall)
}

func (fake *FakeAuthenticator) AuthenticateArgsForCall(i int) *httpnet.Request {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	return fake.authenticateArgsForCall[i].req
}

func (fake *FakeAuthenticator) AuthenticateReturns(result1 *web.UserContext, result2 http.Decision, result3 error) {
	fake.AuthenticateStub = nil
	fake.authenticateReturns = struct {
		result1 *web.UserContext
		result2 http.Decision
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthenticator) AuthenticateReturnsOnCall(i int, result1 *web.UserContext, result2 http.Decision, result3 error) {
	fake.AuthenticateStub = nil
	if fake.authenticateReturnsOnCall == nil {
		fake.authenticateReturnsOnCall = make(map[int]struct {
			result1 *web.UserContext
			result2 http.Decision
			result3 error
		})
	}
	fake.authenticateReturnsOnCall[i] = struct {
		result1 *web.UserContext
		result2 http.Decision
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthenticator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthenticator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ http.Authenticator = new(FakeAuthenticator)
