apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service-manager.fullname" . }}-secret
  labels:
    app: {{ template "service-manager.name" . }}
    chart: {{ template "service-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  uri: {{ include "service-manager.postgresURI" . | b64enc }}
  encryption_key: {{ randAlphaNum 32 | b64enc }}