#!/usr/bin/env bash
# Copyright 2018 The Service Manager Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

declare -A ENV_VARS
while [ $# -gt 0 ]; do
    case "$1" in
    --api.endpoint=*)
        API_ENDPOINT="${1#*=}";;
    --org.name=*)
        ORG_NAME="${1#*=}";;
    --space.name=*)
        SPACE_NAME="${1#*=}";;
    --cf.username=*)
        CF_USERNAME="${1#*=}";;
    --cf.password=*)
        CF_PASSWORD="${1#*=}";;
    --manifest.location=*)
        MANIFEST_LOCATION="${1#*=}";;
    --app.name=*)
        APP_NAME="${1#*=}";;
    --app.username=*)
        ENV_VARS[APP_USERNAME]="${1#*=}";;
    --app.password=*)
        ENV_VARS[APP_PASSWORD]="${1#*=}";;
    --sm.url=*)
        ENV_VARS[SM_URL]="${1#*=}";;
    --sm.user=*)
        ENV_VARS[SM_USER]="${1#*=}";;
    --sm.password=*)
        ENV_VARS[SM_PASSWORD]="${1#*=}";;
    --sm.osb.api.path=*)
        ENV_VARS[SM_OSB_API_PATH]="${1#*=}";;
    --cf.client.username=*)
        ENV_VARS[CF_CLIENT_USERNAME]="${1#*=}";;
    --cf.client-password=*)
        ENV_VARS[CF_CLIENT_PASSWORD]="${1#*=}";;
    *) echo "Invalid option $1"
        exit 1
    esac
    shift
done

cf api ${API_ENDPOINT}
cf auth ${CF_USERNAME} ${CF_PASSWORD}
cf orgs ${ORG_NAME} || cf create-org ${ORG_NAME}
cf target -o ${ORG_NAME}
cf spaces ${SPACE_NAME} || cf create-space ${SPACE_NAME}
cf target -s ${SPACE_NAME}

cf push -f ${MANIFEST_LOCATION} --no-start

for KEY in "${!ENV_VARS[@]}"; do
  cf set-env ${APP_NAME} ${KEY} ${ENV_VARS[$KEY]}
done

cf start ${APP_NAME}