// Code generated by counterfeiter. DO NOT EDIT.
package storagefakes

import (
	"sync"

	"github.com/Peripli/service-manager/pkg/types"
	"github.com/Peripli/service-manager/storage"
)

type FakeCredentials struct {
	GetStub        func(username string) (*types.Credentials, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		username string
	}
	getReturns struct {
		result1 *types.Credentials
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *types.Credentials
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredentials) Get(username string) (*types.Credentials, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		username string
	}{username})
	fake.recordInvocation("Get", []interface{}{username})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(username)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getReturns.result1, fake.getReturns.result2
}

func (fake *FakeCredentials) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeCredentials) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].username
}

func (fake *FakeCredentials) GetReturns(result1 *types.Credentials, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *types.Credentials
		result2 error
	}{result1, result2}
}

func (fake *FakeCredentials) GetReturnsOnCall(i int, result1 *types.Credentials, result2 error) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *types.Credentials
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *types.Credentials
		result2 error
	}{result1, result2}
}

func (fake *FakeCredentials) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredentials) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.Credentials = new(FakeCredentials)
