// Code generated by counterfeiter. DO NOT EDIT.
package storagefakes

import (
	"sync"

	"github.com/Peripli/service-manager/storage"
)

type FakeCreateInterceptor struct {
	AroundTxCreateStub        func(h storage.InterceptCreateAroundTx) storage.InterceptCreateAroundTx
	aroundTxCreateMutex       sync.RWMutex
	aroundTxCreateArgsForCall []struct {
		h storage.InterceptCreateAroundTx
	}
	aroundTxCreateReturns struct {
		result1 storage.InterceptCreateAroundTx
	}
	aroundTxCreateReturnsOnCall map[int]struct {
		result1 storage.InterceptCreateAroundTx
	}
	OnTxCreateStub        func(f storage.InterceptCreateOnTx) storage.InterceptCreateOnTx
	onTxCreateMutex       sync.RWMutex
	onTxCreateArgsForCall []struct {
		f storage.InterceptCreateOnTx
	}
	onTxCreateReturns struct {
		result1 storage.InterceptCreateOnTx
	}
	onTxCreateReturnsOnCall map[int]struct {
		result1 storage.InterceptCreateOnTx
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateInterceptor) AroundTxCreate(h storage.InterceptCreateAroundTx) storage.InterceptCreateAroundTx {
	fake.aroundTxCreateMutex.Lock()
	ret, specificReturn := fake.aroundTxCreateReturnsOnCall[len(fake.aroundTxCreateArgsForCall)]
	fake.aroundTxCreateArgsForCall = append(fake.aroundTxCreateArgsForCall, struct {
		h storage.InterceptCreateAroundTx
	}{h})
	fake.recordInvocation("AroundTxCreate", []interface{}{h})
	fake.aroundTxCreateMutex.Unlock()
	if fake.AroundTxCreateStub != nil {
		return fake.AroundTxCreateStub(h)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.aroundTxCreateReturns.result1
}

func (fake *FakeCreateInterceptor) AroundTxCreateCallCount() int {
	fake.aroundTxCreateMutex.RLock()
	defer fake.aroundTxCreateMutex.RUnlock()
	return len(fake.aroundTxCreateArgsForCall)
}

func (fake *FakeCreateInterceptor) AroundTxCreateArgsForCall(i int) storage.InterceptCreateAroundTx {
	fake.aroundTxCreateMutex.RLock()
	defer fake.aroundTxCreateMutex.RUnlock()
	return fake.aroundTxCreateArgsForCall[i].h
}

func (fake *FakeCreateInterceptor) AroundTxCreateReturns(result1 storage.InterceptCreateAroundTx) {
	fake.AroundTxCreateStub = nil
	fake.aroundTxCreateReturns = struct {
		result1 storage.InterceptCreateAroundTx
	}{result1}
}

func (fake *FakeCreateInterceptor) AroundTxCreateReturnsOnCall(i int, result1 storage.InterceptCreateAroundTx) {
	fake.AroundTxCreateStub = nil
	if fake.aroundTxCreateReturnsOnCall == nil {
		fake.aroundTxCreateReturnsOnCall = make(map[int]struct {
			result1 storage.InterceptCreateAroundTx
		})
	}
	fake.aroundTxCreateReturnsOnCall[i] = struct {
		result1 storage.InterceptCreateAroundTx
	}{result1}
}

func (fake *FakeCreateInterceptor) OnTxCreate(f storage.InterceptCreateOnTx) storage.InterceptCreateOnTx {
	fake.onTxCreateMutex.Lock()
	ret, specificReturn := fake.onTxCreateReturnsOnCall[len(fake.onTxCreateArgsForCall)]
	fake.onTxCreateArgsForCall = append(fake.onTxCreateArgsForCall, struct {
		f storage.InterceptCreateOnTx
	}{f})
	fake.recordInvocation("OnTxCreate", []interface{}{f})
	fake.onTxCreateMutex.Unlock()
	if fake.OnTxCreateStub != nil {
		return fake.OnTxCreateStub(f)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.onTxCreateReturns.result1
}

func (fake *FakeCreateInterceptor) OnTxCreateCallCount() int {
	fake.onTxCreateMutex.RLock()
	defer fake.onTxCreateMutex.RUnlock()
	return len(fake.onTxCreateArgsForCall)
}

func (fake *FakeCreateInterceptor) OnTxCreateArgsForCall(i int) storage.InterceptCreateOnTx {
	fake.onTxCreateMutex.RLock()
	defer fake.onTxCreateMutex.RUnlock()
	return fake.onTxCreateArgsForCall[i].f
}

func (fake *FakeCreateInterceptor) OnTxCreateReturns(result1 storage.InterceptCreateOnTx) {
	fake.OnTxCreateStub = nil
	fake.onTxCreateReturns = struct {
		result1 storage.InterceptCreateOnTx
	}{result1}
}

func (fake *FakeCreateInterceptor) OnTxCreateReturnsOnCall(i int, result1 storage.InterceptCreateOnTx) {
	fake.OnTxCreateStub = nil
	if fake.onTxCreateReturnsOnCall == nil {
		fake.onTxCreateReturnsOnCall = make(map[int]struct {
			result1 storage.InterceptCreateOnTx
		})
	}
	fake.onTxCreateReturnsOnCall[i] = struct {
		result1 storage.InterceptCreateOnTx
	}{result1}
}

func (fake *FakeCreateInterceptor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.aroundTxCreateMutex.RLock()
	defer fake.aroundTxCreateMutex.RUnlock()
	fake.onTxCreateMutex.RLock()
	defer fake.onTxCreateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCreateInterceptor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.CreateInterceptor = new(FakeCreateInterceptor)
