// Code generated by counterfeiter. DO NOT EDIT.
package storagefakes

import (
	"sync"

	"github.wdf.sap.corp/SvcManager/sm-sap/peripli/service-manager/storage"
)

type FakeCreateOnTxInterceptor struct {
	OnTxCreateStub        func(storage.InterceptCreateOnTxFunc) storage.InterceptCreateOnTxFunc
	onTxCreateMutex       sync.RWMutex
	onTxCreateArgsForCall []struct {
		arg1 storage.InterceptCreateOnTxFunc
	}
	onTxCreateReturns struct {
		result1 storage.InterceptCreateOnTxFunc
	}
	onTxCreateReturnsOnCall map[int]struct {
		result1 storage.InterceptCreateOnTxFunc
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateOnTxInterceptor) OnTxCreate(arg1 storage.InterceptCreateOnTxFunc) storage.InterceptCreateOnTxFunc {
	fake.onTxCreateMutex.Lock()
	ret, specificReturn := fake.onTxCreateReturnsOnCall[len(fake.onTxCreateArgsForCall)]
	fake.onTxCreateArgsForCall = append(fake.onTxCreateArgsForCall, struct {
		arg1 storage.InterceptCreateOnTxFunc
	}{arg1})
	stub := fake.OnTxCreateStub
	fakeReturns := fake.onTxCreateReturns
	fake.recordInvocation("OnTxCreate", []interface{}{arg1})
	fake.onTxCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCreateOnTxInterceptor) OnTxCreateCallCount() int {
	fake.onTxCreateMutex.RLock()
	defer fake.onTxCreateMutex.RUnlock()
	return len(fake.onTxCreateArgsForCall)
}

func (fake *FakeCreateOnTxInterceptor) OnTxCreateCalls(stub func(storage.InterceptCreateOnTxFunc) storage.InterceptCreateOnTxFunc) {
	fake.onTxCreateMutex.Lock()
	defer fake.onTxCreateMutex.Unlock()
	fake.OnTxCreateStub = stub
}

func (fake *FakeCreateOnTxInterceptor) OnTxCreateArgsForCall(i int) storage.InterceptCreateOnTxFunc {
	fake.onTxCreateMutex.RLock()
	defer fake.onTxCreateMutex.RUnlock()
	argsForCall := fake.onTxCreateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCreateOnTxInterceptor) OnTxCreateReturns(result1 storage.InterceptCreateOnTxFunc) {
	fake.onTxCreateMutex.Lock()
	defer fake.onTxCreateMutex.Unlock()
	fake.OnTxCreateStub = nil
	fake.onTxCreateReturns = struct {
		result1 storage.InterceptCreateOnTxFunc
	}{result1}
}

func (fake *FakeCreateOnTxInterceptor) OnTxCreateReturnsOnCall(i int, result1 storage.InterceptCreateOnTxFunc) {
	fake.onTxCreateMutex.Lock()
	defer fake.onTxCreateMutex.Unlock()
	fake.OnTxCreateStub = nil
	if fake.onTxCreateReturnsOnCall == nil {
		fake.onTxCreateReturnsOnCall = make(map[int]struct {
			result1 storage.InterceptCreateOnTxFunc
		})
	}
	fake.onTxCreateReturnsOnCall[i] = struct {
		result1 storage.InterceptCreateOnTxFunc
	}{result1}
}

func (fake *FakeCreateOnTxInterceptor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.onTxCreateMutex.RLock()
	defer fake.onTxCreateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCreateOnTxInterceptor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.CreateOnTxInterceptor = new(FakeCreateOnTxInterceptor)
