// Code generated by counterfeiter. DO NOT EDIT.
package storagefakes

import (
	"sync"

	"github.com/Peripli/service-manager/storage"
)

type FakeCreateAroundTxInterceptor struct {
	AroundTxCreateStub        func(storage.InterceptCreateAroundTxFunc) storage.InterceptCreateAroundTxFunc
	aroundTxCreateMutex       sync.RWMutex
	aroundTxCreateArgsForCall []struct {
		arg1 storage.InterceptCreateAroundTxFunc
	}
	aroundTxCreateReturns struct {
		result1 storage.InterceptCreateAroundTxFunc
	}
	aroundTxCreateReturnsOnCall map[int]struct {
		result1 storage.InterceptCreateAroundTxFunc
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateAroundTxInterceptor) AroundTxCreate(arg1 storage.InterceptCreateAroundTxFunc) storage.InterceptCreateAroundTxFunc {
	fake.aroundTxCreateMutex.Lock()
	ret, specificReturn := fake.aroundTxCreateReturnsOnCall[len(fake.aroundTxCreateArgsForCall)]
	fake.aroundTxCreateArgsForCall = append(fake.aroundTxCreateArgsForCall, struct {
		arg1 storage.InterceptCreateAroundTxFunc
	}{arg1})
	stub := fake.AroundTxCreateStub
	fakeReturns := fake.aroundTxCreateReturns
	fake.recordInvocation("AroundTxCreate", []interface{}{arg1})
	fake.aroundTxCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCreateAroundTxInterceptor) AroundTxCreateCallCount() int {
	fake.aroundTxCreateMutex.RLock()
	defer fake.aroundTxCreateMutex.RUnlock()
	return len(fake.aroundTxCreateArgsForCall)
}

func (fake *FakeCreateAroundTxInterceptor) AroundTxCreateCalls(stub func(storage.InterceptCreateAroundTxFunc) storage.InterceptCreateAroundTxFunc) {
	fake.aroundTxCreateMutex.Lock()
	defer fake.aroundTxCreateMutex.Unlock()
	fake.AroundTxCreateStub = stub
}

func (fake *FakeCreateAroundTxInterceptor) AroundTxCreateArgsForCall(i int) storage.InterceptCreateAroundTxFunc {
	fake.aroundTxCreateMutex.RLock()
	defer fake.aroundTxCreateMutex.RUnlock()
	argsForCall := fake.aroundTxCreateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCreateAroundTxInterceptor) AroundTxCreateReturns(result1 storage.InterceptCreateAroundTxFunc) {
	fake.aroundTxCreateMutex.Lock()
	defer fake.aroundTxCreateMutex.Unlock()
	fake.AroundTxCreateStub = nil
	fake.aroundTxCreateReturns = struct {
		result1 storage.InterceptCreateAroundTxFunc
	}{result1}
}

func (fake *FakeCreateAroundTxInterceptor) AroundTxCreateReturnsOnCall(i int, result1 storage.InterceptCreateAroundTxFunc) {
	fake.aroundTxCreateMutex.Lock()
	defer fake.aroundTxCreateMutex.Unlock()
	fake.AroundTxCreateStub = nil
	if fake.aroundTxCreateReturnsOnCall == nil {
		fake.aroundTxCreateReturnsOnCall = make(map[int]struct {
			result1 storage.InterceptCreateAroundTxFunc
		})
	}
	fake.aroundTxCreateReturnsOnCall[i] = struct {
		result1 storage.InterceptCreateAroundTxFunc
	}{result1}
}

func (fake *FakeCreateAroundTxInterceptor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.aroundTxCreateMutex.RLock()
	defer fake.aroundTxCreateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCreateAroundTxInterceptor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.CreateAroundTxInterceptor = new(FakeCreateAroundTxInterceptor)
