/*
 * Copyright 2018 The Service Manager Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by counterfeiter. DO NOT EDIT.
package platformfakes

import (
	"context"
	"encoding/json"
	"sync"

	"github.com/Peripli/service-manager/pkg/sbproxy/platform"
)

type FakeServiceAccess struct {
	EnableAccessForServiceStub        func(ctx context.Context, data json.RawMessage, serviceGUID string) error
	enableAccessForServiceMutex       sync.RWMutex
	enableAccessForServiceArgsForCall []struct {
		ctx         context.Context
		data        json.RawMessage
		serviceGUID string
	}
	enableAccessForServiceReturns struct {
		result1 error
	}
	enableAccessForServiceReturnsOnCall map[int]struct {
		result1 error
	}
	EnableAccessForPlanStub        func(ctx context.Context, data json.RawMessage, servicePlanGUID string) error
	enableAccessForPlanMutex       sync.RWMutex
	enableAccessForPlanArgsForCall []struct {
		ctx             context.Context
		data            json.RawMessage
		servicePlanGUID string
	}
	enableAccessForPlanReturns struct {
		result1 error
	}
	enableAccessForPlanReturnsOnCall map[int]struct {
		result1 error
	}
	DisableAccessForServiceStub        func(ctx context.Context, data json.RawMessage, serviceGUID string) error
	disableAccessForServiceMutex       sync.RWMutex
	disableAccessForServiceArgsForCall []struct {
		ctx         context.Context
		data        json.RawMessage
		serviceGUID string
	}
	disableAccessForServiceReturns struct {
		result1 error
	}
	disableAccessForServiceReturnsOnCall map[int]struct {
		result1 error
	}
	DisableAccessForPlanStub        func(ctx context.Context, data json.RawMessage, servicePlanGUID string) error
	disableAccessForPlanMutex       sync.RWMutex
	disableAccessForPlanArgsForCall []struct {
		ctx             context.Context
		data            json.RawMessage
		servicePlanGUID string
	}
	disableAccessForPlanReturns struct {
		result1 error
	}
	disableAccessForPlanReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceAccess) EnableAccessForService(ctx context.Context, data json.RawMessage, serviceGUID string) error {
	fake.enableAccessForServiceMutex.Lock()
	ret, specificReturn := fake.enableAccessForServiceReturnsOnCall[len(fake.enableAccessForServiceArgsForCall)]
	fake.enableAccessForServiceArgsForCall = append(fake.enableAccessForServiceArgsForCall, struct {
		ctx         context.Context
		data        json.RawMessage
		serviceGUID string
	}{ctx, data, serviceGUID})
	fake.recordInvocation("EnableAccessForService", []interface{}{ctx, data, serviceGUID})
	fake.enableAccessForServiceMutex.Unlock()
	if fake.EnableAccessForServiceStub != nil {
		return fake.EnableAccessForServiceStub(ctx, data, serviceGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.enableAccessForServiceReturns.result1
}

func (fake *FakeServiceAccess) EnableAccessForServiceCallCount() int {
	fake.enableAccessForServiceMutex.RLock()
	defer fake.enableAccessForServiceMutex.RUnlock()
	return len(fake.enableAccessForServiceArgsForCall)
}

func (fake *FakeServiceAccess) EnableAccessForServiceArgsForCall(i int) (context.Context, json.RawMessage, string) {
	fake.enableAccessForServiceMutex.RLock()
	defer fake.enableAccessForServiceMutex.RUnlock()
	return fake.enableAccessForServiceArgsForCall[i].ctx, fake.enableAccessForServiceArgsForCall[i].data, fake.enableAccessForServiceArgsForCall[i].serviceGUID
}

func (fake *FakeServiceAccess) EnableAccessForServiceReturns(result1 error) {
	fake.EnableAccessForServiceStub = nil
	fake.enableAccessForServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) EnableAccessForServiceReturnsOnCall(i int, result1 error) {
	fake.EnableAccessForServiceStub = nil
	if fake.enableAccessForServiceReturnsOnCall == nil {
		fake.enableAccessForServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.enableAccessForServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) EnableAccessForPlan(ctx context.Context, data json.RawMessage, servicePlanGUID string) error {
	fake.enableAccessForPlanMutex.Lock()
	ret, specificReturn := fake.enableAccessForPlanReturnsOnCall[len(fake.enableAccessForPlanArgsForCall)]
	fake.enableAccessForPlanArgsForCall = append(fake.enableAccessForPlanArgsForCall, struct {
		ctx             context.Context
		data            json.RawMessage
		servicePlanGUID string
	}{ctx, data, servicePlanGUID})
	fake.recordInvocation("EnableAccessForPlan", []interface{}{ctx, data, servicePlanGUID})
	fake.enableAccessForPlanMutex.Unlock()
	if fake.EnableAccessForPlanStub != nil {
		return fake.EnableAccessForPlanStub(ctx, data, servicePlanGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.enableAccessForPlanReturns.result1
}

func (fake *FakeServiceAccess) EnableAccessForPlanCallCount() int {
	fake.enableAccessForPlanMutex.RLock()
	defer fake.enableAccessForPlanMutex.RUnlock()
	return len(fake.enableAccessForPlanArgsForCall)
}

func (fake *FakeServiceAccess) EnableAccessForPlanArgsForCall(i int) (context.Context, json.RawMessage, string) {
	fake.enableAccessForPlanMutex.RLock()
	defer fake.enableAccessForPlanMutex.RUnlock()
	return fake.enableAccessForPlanArgsForCall[i].ctx, fake.enableAccessForPlanArgsForCall[i].data, fake.enableAccessForPlanArgsForCall[i].servicePlanGUID
}

func (fake *FakeServiceAccess) EnableAccessForPlanReturns(result1 error) {
	fake.EnableAccessForPlanStub = nil
	fake.enableAccessForPlanReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) EnableAccessForPlanReturnsOnCall(i int, result1 error) {
	fake.EnableAccessForPlanStub = nil
	if fake.enableAccessForPlanReturnsOnCall == nil {
		fake.enableAccessForPlanReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.enableAccessForPlanReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) DisableAccessForService(ctx context.Context, data json.RawMessage, serviceGUID string) error {
	fake.disableAccessForServiceMutex.Lock()
	ret, specificReturn := fake.disableAccessForServiceReturnsOnCall[len(fake.disableAccessForServiceArgsForCall)]
	fake.disableAccessForServiceArgsForCall = append(fake.disableAccessForServiceArgsForCall, struct {
		ctx         context.Context
		data        json.RawMessage
		serviceGUID string
	}{ctx, data, serviceGUID})
	fake.recordInvocation("DisableAccessForService", []interface{}{ctx, data, serviceGUID})
	fake.disableAccessForServiceMutex.Unlock()
	if fake.DisableAccessForServiceStub != nil {
		return fake.DisableAccessForServiceStub(ctx, data, serviceGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.disableAccessForServiceReturns.result1
}

func (fake *FakeServiceAccess) DisableAccessForServiceCallCount() int {
	fake.disableAccessForServiceMutex.RLock()
	defer fake.disableAccessForServiceMutex.RUnlock()
	return len(fake.disableAccessForServiceArgsForCall)
}

func (fake *FakeServiceAccess) DisableAccessForServiceArgsForCall(i int) (context.Context, json.RawMessage, string) {
	fake.disableAccessForServiceMutex.RLock()
	defer fake.disableAccessForServiceMutex.RUnlock()
	return fake.disableAccessForServiceArgsForCall[i].ctx, fake.disableAccessForServiceArgsForCall[i].data, fake.disableAccessForServiceArgsForCall[i].serviceGUID
}

func (fake *FakeServiceAccess) DisableAccessForServiceReturns(result1 error) {
	fake.DisableAccessForServiceStub = nil
	fake.disableAccessForServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) DisableAccessForServiceReturnsOnCall(i int, result1 error) {
	fake.DisableAccessForServiceStub = nil
	if fake.disableAccessForServiceReturnsOnCall == nil {
		fake.disableAccessForServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.disableAccessForServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) DisableAccessForPlan(ctx context.Context, data json.RawMessage, servicePlanGUID string) error {
	fake.disableAccessForPlanMutex.Lock()
	ret, specificReturn := fake.disableAccessForPlanReturnsOnCall[len(fake.disableAccessForPlanArgsForCall)]
	fake.disableAccessForPlanArgsForCall = append(fake.disableAccessForPlanArgsForCall, struct {
		ctx             context.Context
		data            json.RawMessage
		servicePlanGUID string
	}{ctx, data, servicePlanGUID})
	fake.recordInvocation("DisableAccessForPlan", []interface{}{ctx, data, servicePlanGUID})
	fake.disableAccessForPlanMutex.Unlock()
	if fake.DisableAccessForPlanStub != nil {
		return fake.DisableAccessForPlanStub(ctx, data, servicePlanGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.disableAccessForPlanReturns.result1
}

func (fake *FakeServiceAccess) DisableAccessForPlanCallCount() int {
	fake.disableAccessForPlanMutex.RLock()
	defer fake.disableAccessForPlanMutex.RUnlock()
	return len(fake.disableAccessForPlanArgsForCall)
}

func (fake *FakeServiceAccess) DisableAccessForPlanArgsForCall(i int) (context.Context, json.RawMessage, string) {
	fake.disableAccessForPlanMutex.RLock()
	defer fake.disableAccessForPlanMutex.RUnlock()
	return fake.disableAccessForPlanArgsForCall[i].ctx, fake.disableAccessForPlanArgsForCall[i].data, fake.disableAccessForPlanArgsForCall[i].servicePlanGUID
}

func (fake *FakeServiceAccess) DisableAccessForPlanReturns(result1 error) {
	fake.DisableAccessForPlanStub = nil
	fake.disableAccessForPlanReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) DisableAccessForPlanReturnsOnCall(i int, result1 error) {
	fake.DisableAccessForPlanStub = nil
	if fake.disableAccessForPlanReturnsOnCall == nil {
		fake.disableAccessForPlanReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.disableAccessForPlanReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAccess) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.enableAccessForServiceMutex.RLock()
	defer fake.enableAccessForServiceMutex.RUnlock()
	fake.enableAccessForPlanMutex.RLock()
	defer fake.enableAccessForPlanMutex.RUnlock()
	fake.disableAccessForServiceMutex.RLock()
	defer fake.disableAccessForServiceMutex.RUnlock()
	fake.disableAccessForPlanMutex.RLock()
	defer fake.disableAccessForPlanMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceAccess) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ platform.ServiceAccess = new(FakeServiceAccess)
