replicaCount: 1

image:
  repository: quay.io/service-manager/core
  tag: v0.5.1
  pullPolicy: IfNotPresent
  #pullsecret: <>

service:
  type: ClusterIP
  port: 80

securityContext: {}

ingress:
  enabled: true
  host: local.service-manager
  tls: {}
    # secretName: ***

#externalPostgresURI: postgres://<pguser>:<pgpassword>@<pghost>:<pgport>/postgres?sslmode=disable

postgresql:
  install: true
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  persistence:
    size: 1Gi

storage:
#  migrations_url: <migration_url>
  encryption_key: ejHjRNHbS0NaqARSRvnweVV9zcmhQEa8

file:
  name: application
  location: /etc/config
  format: yml

config:
  log:
    level: info
    format: text
  server:
    request_timeout: 4000ms
    shutdown_timeout: 4000ms
  httpclient:
    skip_ssl_validation: true # to be false
  api:
    token_issuer_url: https://uaa.dev.cfdev.sh
  storage:
    max_idle_connections: 5
