replicaCount: 1

image:
  repository: quay.io/service-manager/core
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: local.service-manager
  tls: {}
    # secretName: ***

#externalPostgresURI: postgres://<pguser>:<pgpassword>@<pghost>:<pgport>/postgres?sslmode=disable

postgresql:
  install: true
  postgresUser: pguser
  postgresPassword: pgpassword
  persistence:
    size: 1Gi

storage:
  migrations_url: ""
  skip_ssl_validation: false

file:
  name: application
  location: /etc/config
  format: yml

config:
  log:
    level: info
    format: text
  server:
    request_timeout: 3000ms
    shutdown_timeout: 3000ms
  api:
    token_issuer_url: https://uaa.dev.cfdev.sh
    client_id: cf
    skip_ssl_validation: false
