BEGIN;

ALTER TABLE brokers ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';
ALTER TABLE operations ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';
ALTER TABLE platforms ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';
ALTER TABLE service_offerings ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';
ALTER TABLE service_plans ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';
ALTER TABLE visibilities ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT '1';

COMMIT;