BEGIN;

ALTER TABLE operations ADD COLUMN IF NOT EXISTS root_id varchar(100);
ALTER TABLE operations ADD COLUMN IF NOT EXISTS cascade BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE operations ADD COLUMN IF NOT EXISTS parent_id varchar(100);

ALTER TYPE operation_state ADD VALUE 'pending';

COMMIT;