// Code generated by counterfeiter. DO NOT EDIT.
package webfakes

import (
	"sync"

	"github.com/Peripli/service-manager/pkg/web"
)

type FakeData struct {
	DataStub        func(interface{}) error
	dataMutex       sync.RWMutex
	dataArgsForCall []struct {
		arg1 interface{}
	}
	dataReturns struct {
		result1 error
	}
	dataReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeData) Data(arg1 interface{}) error {
	fake.dataMutex.Lock()
	ret, specificReturn := fake.dataReturnsOnCall[len(fake.dataArgsForCall)]
	fake.dataArgsForCall = append(fake.dataArgsForCall, struct {
		arg1 interface{}
	}{arg1})
	fake.recordInvocation("Data", []interface{}{arg1})
	fake.dataMutex.Unlock()
	if fake.DataStub != nil {
		return fake.DataStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.dataReturns
	return fakeReturns.result1
}

func (fake *FakeData) DataCallCount() int {
	fake.dataMutex.RLock()
	defer fake.dataMutex.RUnlock()
	return len(fake.dataArgsForCall)
}

func (fake *FakeData) DataCalls(stub func(interface{}) error) {
	fake.dataMutex.Lock()
	defer fake.dataMutex.Unlock()
	fake.DataStub = stub
}

func (fake *FakeData) DataArgsForCall(i int) interface{} {
	fake.dataMutex.RLock()
	defer fake.dataMutex.RUnlock()
	argsForCall := fake.dataArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeData) DataReturns(result1 error) {
	fake.dataMutex.Lock()
	defer fake.dataMutex.Unlock()
	fake.DataStub = nil
	fake.dataReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeData) DataReturnsOnCall(i int, result1 error) {
	fake.dataMutex.Lock()
	defer fake.dataMutex.Unlock()
	fake.DataStub = nil
	if fake.dataReturnsOnCall == nil {
		fake.dataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.dataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeData) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.dataMutex.RLock()
	defer fake.dataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeData) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ web.Data = new(FakeData)
